/* Generated By:JavaCC: Do not edit this line. CalculatorTreeConstants.java Version 6.0_1 */
public interface CalculatorTreeConstants
{
  public int JJTEXPRESSION = 0;


  public String[] jjtNodeName = {
    "Expression",
  };
}
/* JavaCC - OriginalChecksum=71f4bf98c415a1f8a0b3a19d4a9ba964 (do not edit this line) */
