/* Generated By:JavaCC: Do not edit this line. ExpressionParsingTreeConstants.java Version 6.0_1 */
public interface ExpressionParsingTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTVOID = 1;
  public int JJTVARTERM = 2;
  public int JJTEXPR3 = 3;


  public String[] jjtNodeName = {
    "Expression",
    "void",
    "VarTerm",
    "Expr3",
  };
}
/* JavaCC - OriginalChecksum=56ae25ffdefa1834fafea634de6cc962 (do not edit this line) */
