/* Generated By:JJTree&JavaCC: Do not edit this line. ExpressionParsingConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExpressionParsingConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int OPERATORS = 4;
  /** RegularExpression Id. */
  int BRACKETOPEN = 5;
  /** RegularExpression Id. */
  int BRACKETCLOSE = 6;
  /** RegularExpression Id. */
  int FULLSTOP = 7;
  /** RegularExpression Id. */
  int COMMA = 8;
  /** RegularExpression Id. */
  int NOT = 9;
  /** RegularExpression Id. */
  int ROUNDBRACKETOPEN = 10;
  /** RegularExpression Id. */
  int ROUNDBRACKETCLOSED = 11;
  /** RegularExpression Id. */
  int TRUE = 12;
  /** RegularExpression Id. */
  int FALSE = 13;
  /** RegularExpression Id. */
  int THIS = 14;
  /** RegularExpression Id. */
  int LENGTH = 15;
  /** RegularExpression Id. */
  int NEW = 16;
  /** RegularExpression Id. */
  int INT = 17;
  /** RegularExpression Id. */
  int INTEGERLITERAL = 18;
  /** RegularExpression Id. */
  int IDENTIFIER = 19;
  /** RegularExpression Id. */
  int LF = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "<OPERATORS>",
    "\"[\"",
    "\"]\"",
    "\".\"",
    "\",\"",
    "\"!\"",
    "\"(\"",
    "\")\"",
    "\"true\"",
    "\"false\"",
    "\"this\"",
    "\"length\"",
    "\"new\"",
    "\"int\"",
    "<INTEGERLITERAL>",
    "<IDENTIFIER>",
    "\"\\n\"",
  };

}
