/* Generated By:JavaCC: Do not edit this line. ExpressionParsingTreeConstants.java Version 6.0_1 */
public interface ExpressionParsingTreeConstants
{
  public int JJTEXPRESSION = 0;


  public String[] jjtNodeName = {
    "Expression",
  };
}
/* JavaCC - OriginalChecksum=908a239c53de2e9f190006772ed725e7 (do not edit this line) */
