/* Generated By:JavaCC: Do not edit this line. NewJavaTreeConstants.java Version 6.0_1 */
public interface NewJavaTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTCLASS = 1;
  public int JJTEXTENDS = 2;
  public int JJTVAR = 3;
  public int JJTTYPE = 4;
  public int JJTMAIN = 5;
  public int JJTFUNCTION = 6;
  public int JJTRETURN = 7;
  public int JJTARGS = 8;
  public int JJTVOID = 9;
  public int JJTASSIGN = 10;
  public int JJTARRINDEX = 11;
  public int JJTIF = 12;
  public int JJTELSE = 13;
  public int JJTWHILE = 14;
  public int JJTOP2 = 15;
  public int JJTFULLSTOP = 16;
  public int JJTOP3 = 17;
  public int JJTOP4 = 18;
  public int JJTOP5 = 19;
  public int JJTPAREMETER = 20;
  public int JJTVAL = 21;
  public int JJTTEXT = 22;
  public int JJTTRUE = 23;
  public int JJTFALSE = 24;
  public int JJTTHIS = 25;
  public int JJTNEW = 26;
  public int JJTNOT = 27;


  public String[] jjtNodeName = {
    "Program",
    "CLASS",
    "EXTENDS",
    "VAR",
    "TYPE",
    "MAIN",
    "FUNCTION",
    "RETURN",
    "ARGS",
    "void",
    "ASSIGN",
    "ARRINDEX",
    "IF",
    "ELSE",
    "WHILE",
    "OP2",
    "FULLSTOP",
    "OP3",
    "OP4",
    "OP5",
    "PAREMETER",
    "VAL",
    "TEXT",
    "TRUE",
    "FALSE",
    "THIS",
    "NEW",
    "NOT",
  };
}
/* JavaCC - OriginalChecksum=7347db2660b8bc4aaa8f49983e082160 (do not edit this line) */
