/* Generated By:JJTree&JavaCC: Do not edit this line. NewJavaConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface NewJavaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CLASS = 6;
  /** RegularExpression Id. */
  int EXTENDS = 7;
  /** RegularExpression Id. */
  int OPERATORS = 8;
  /** RegularExpression Id. */
  int BRACKETOPEN = 9;
  /** RegularExpression Id. */
  int BRACKETCLOSE = 10;
  /** RegularExpression Id. */
  int FULLSTOP = 11;
  /** RegularExpression Id. */
  int COMMA = 12;
  /** RegularExpression Id. */
  int SEMICOLON = 13;
  /** RegularExpression Id. */
  int NOT = 14;
  /** RegularExpression Id. */
  int ROUNDBRACKETOPEN = 15;
  /** RegularExpression Id. */
  int ROUNDBRACKETCLOSED = 16;
  /** RegularExpression Id. */
  int CURLYBRACKETOPENED = 17;
  /** RegularExpression Id. */
  int CURLYBRACKETCLOSED = 18;
  /** RegularExpression Id. */
  int ASSERT = 19;
  /** RegularExpression Id. */
  int TRUE = 20;
  /** RegularExpression Id. */
  int FALSE = 21;
  /** RegularExpression Id. */
  int THIS = 22;
  /** RegularExpression Id. */
  int NEW = 23;
  /** RegularExpression Id. */
  int LENGTH = 24;
  /** RegularExpression Id. */
  int INT = 25;
  /** RegularExpression Id. */
  int PUBLIC = 26;
  /** RegularExpression Id. */
  int STATIC = 27;
  /** RegularExpression Id. */
  int VOID = 28;
  /** RegularExpression Id. */
  int MAIN = 29;
  /** RegularExpression Id. */
  int RETURN = 30;
  /** RegularExpression Id. */
  int STRING = 31;
  /** RegularExpression Id. */
  int BOOLEAN = 32;
  /** RegularExpression Id. */
  int IF = 33;
  /** RegularExpression Id. */
  int ELSE = 34;
  /** RegularExpression Id. */
  int WHILE = 35;
  /** RegularExpression Id. */
  int INTEGERLITERAL = 36;
  /** RegularExpression Id. */
  int IDENTIFIER = 37;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\n \"",
    "\"class\"",
    "\"extends\"",
    "<OPERATORS>",
    "\"[\"",
    "\"]\"",
    "\".\"",
    "\",\"",
    "\";\"",
    "\"!\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"=\"",
    "\"true\"",
    "\"false\"",
    "\"this\"",
    "\"new\"",
    "\"length\"",
    "\"int\"",
    "\"public\"",
    "\"static\"",
    "\"void\"",
    "\"main\"",
    "\"return\"",
    "\"String\"",
    "\"boolean\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "<INTEGERLITERAL>",
    "<IDENTIFIER>",
  };

}
