/* Generated By:JavaCC: Do not edit this line. NewJavaTreeConstants.java Version 6.0_1 */
public interface NewJavaTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTCLASS = 1;
  public int JJTVAR = 2;
  public int JJTTYPE = 3;
  public int JJTMAIN = 4;
  public int JJTFUNCTION = 5;
  public int JJTARGS = 6;
  public int JJTRETURN = 7;
  public int JJTVOID = 8;
  public int JJTASSIGN = 9;
  public int JJTIF = 10;
  public int JJTELSE = 11;
  public int JJTWHILE = 12;
  public int JJTFULLSTOP = 13;
  public int JJTOP = 14;
  public int JJTPAREMETER = 15;
  public int JJTVAL = 16;
  public int JJTTEXT = 17;
  public int JJTTRUE = 18;
  public int JJTFALSE = 19;
  public int JJTTHIS = 20;
  public int JJTNEW = 21;
  public int JJTNOT = 22;
  public int JJTBRACKETS = 23;


  public String[] jjtNodeName = {
    "Program",
    "CLASS",
    "VAR",
    "TYPE",
    "MAIN",
    "FUNCTION",
    "ARGS",
    "RETURN",
    "void",
    "ASSIGN",
    "IF",
    "ELSE",
    "WHILE",
    "FULLSTOP",
    "OP",
    "PAREMETER",
    "VAL",
    "TEXT",
    "TRUE",
    "FALSE",
    "THIS",
    "NEW",
    "NOT",
    "BRACKETS",
  };
}
/* JavaCC - OriginalChecksum=3c542617b3df6d86f09f7a505e2e0613 (do not edit this line) */
