/* Generated By:JavaCC: Do not edit this line. NewJavaTreeConstants.java Version 6.0_1 */
public interface NewJavaTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTVAR = 2;
  public int JJTMAIN = 3;
  public int JJTFUNCTION = 4;
  public int JJTRETURN = 5;
  public int JJTASSERT = 6;
  public int JJTIF = 7;
  public int JJTWHILE = 8;
  public int JJTOP = 9;
  public int JJTVAL = 10;
  public int JJTTEXT = 11;
  public int JJTTRUE = 12;
  public int JJTFALSE = 13;
  public int JJTTHIS = 14;
  public int JJTNEW = 15;
  public int JJTNOT = 16;
  public int JJTBRACKETS = 17;


  public String[] jjtNodeName = {
    "Program",
    "void",
    "VAR",
    "MAIN",
    "FUNCTION",
    "RETURN",
    "ASSERT",
    "IF",
    "WHILE",
    "OP",
    "VAL",
    "TEXT",
    "TRUE",
    "FALSE",
    "THIS",
    "NEW",
    "NOT",
    "BRACKETS",
  };
}
/* JavaCC - OriginalChecksum=932a82bf036ae4fcff3fd4d33194db00 (do not edit this line) */
